### ISSUE TITLE
Optimization always failed

### ISSUE THREAD

**Issue by howlfwq** [qubekit/QUBEKit#314]
Hi,
I tried a molecule with 63 atoms. And I keep getting this error:"qubekit.utils.exceptions.WorkFlowExecutionError: The workflow stopped unexpectedly due to the following error at stage: optimisation". The content in the QUBEKit.err file was copied in the following paragraph. Do you know what causes this? And how can I fix this? If you need more information about this error, please let me know. I really appreciate your help. 

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/engines/geometry_optimiser.py", line 155, in optimise
    result_mol = self._handle_output(molecule=molecule, opt_output=opt_result)
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/engines/geometry_optimiser.py", line 211, in _handle_output
    result_mol.to_file(file_name="opt.xyz")
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/molecules/ligand.py", line 220, in to_file
    return RDKit.mol_to_file(rdkit_mol=self.to_rdkit(), file_name=file_name)
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/molecules/ligand.py", line 927, in to_rdkit
    assert qb_atom.stereochemistry == rd_atom.GetProp(
KeyError: '_CIPCode'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/workflow/workflow.py", line 335, in _run_stage
    result_mol = stage.run(
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/workflow/helper_stages.py", line 130, in run
    preopt_geometries = self._pre_opt(
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/site-packages/qubekit/workflow/helper_stages.py", line 250, in _pre_opt
    result_mol, opt_result = result.get()
  File "/home/user/miniconda3/envs/qubekit/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: '_CIPCode'

**Comment by jthorton** [comment]
Hi @howlfwq thanks for opening the issue, it looks like QUBEKit is struggling to keep track of the stereochemistry information in the molecule meaning its not round-tripping to rdkit and back. Are you able to share the molecule so that I can look into it, if not I would make sure the input molecule has all stereochemistry fully defined via smiles or 3D sdf if possible? It could be that the stereochemistry is just too complex for the simple model we have in QUBEKit and we may need to look for ways around this.

**Comment by howlfwq** [comment]
> Hi @jthorton thank you for your help. I have tried pdb, mol2, and sdf file with their connectivity info in the files. But I still got this error. I still don't know how to fix it.

**Comment by jthorton** [comment]
Hi @howlfwq are you able to share the molecule either as a file or as a smiles string so that I can look into it? I would also check that the stereochemistry is entirely defined by passing it to the openff-toolkit and looking for warnings/errors about stereochemistry if not you can use the toolkit to enumerate the stereocenters and feed your desired molecule into qubekit.

**Comment by howlfwq** [comment]
Hi @jthorton Thanks a lot. I finally made my moleule run. I need to modify the conjugate structures of the molecule, ie. all the double and single bonds in the ring and around the N atom, etc. I also tried openff_bespokefit. It includes a fragmentation process for torsion fit. The reference data can be calculated by XTB, ANI, or Psi4. Other than that, is it similiar to qubekit?

**Comment by jthorton** [comment]
Thats great news glad you were able to get it to work, ill close the issue for now then feel free to open again if you have more trouble.

> The reference data can be calculated by XTB, ANI, or Psi4. Other than that, is it similar to qubekit?

They are slightly different in that BepokeFit can give bespoke torsions for OpenFF force fields whereas qubekit gives an almost entirely custom force field, so new bonds, angles torsions, charges and LJ parameters. It also has the ability to provide virtual sites when needed so it depends what kind of parameter optimisation you are looking for, hope this helps!
