### ISSUE TITLE
Got stuck in torsion_scanner

### ISSUE THREAD

**Issue by howlfwq** [qubekit/QUBEKit#347]
Hi @jthorton ,
I 'm running qubekit on a molecule using g09. The method I used is protocol 1a. All optimization, hessian calculations work well. During the torsion scanner, in the first dihedral bond (SCAN_8_9_10_11), it finished normally. However, in the second dehedral bond (SCAN_1_2_4_5), it got stuck in the grid_point_180_job_2. It generated the gaussion input(.com) file, and no results for a few days. No error is reported either. I tried restarting from the torsion_scanner and it got stuck in the same place. I also tried using g09 to just calculate the gasussin input file. It terminated normally and only took 27 mins. Could you help me figure out why it happended and how to solve it?
[lig.txt](https://github.com/qubekit/QUBEKit/files/9937556/lig.txt)
[config_b3lyp.txt](https://github.com/qubekit/QUBEKit/files/9937558/config_b3lyp.txt)
[workflow_result.txt](https://github.com/qubekit/QUBEKit/files/9937562/workflow_result.txt)

**Comment by jthorton** [comment]
Hi @howlfwq thanks for opening the issue I can see that your molecule is quite large and has many flexible bonds and so the torsion scans can be very slow and take a long time to run. To help with this we have recently introduced a fragmentation scheme to try and reduce the time taken to generate the torsion data. Could you try and install qubekit from the main branch and try out this new method to see if it helps your use case? Note you will need to start a new run for this molecule and fragmentation should automatically be included.

**Comment by bieniekmateusz** [comment]
Hi @howlfwq , to add to this, could you also check with `conda list` which `_openmp_mutex` you have? I found that I had to use switch to `conda install _openmp_mutex=4.5=1_llvm` because the gcc version was ending up in a deadlock.

**Comment by howlfwq** [comment]
Hi @jthorton, I intalled the newest version of qubekit. But I could't get it run. Here is the error message I got:
Traceback (most recent call last):
  File "/public/home/user/anaconda3/envs/qubekit_v01/bin/QUBEKit", line 33, in <module>
    sys.exit(load_entry_point('qubekit', 'console_scripts', 'QUBEKit')())
  File "/public/home/user/anaconda3/envs/qubekit_v01/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/user/anaconda3/envs/qubekit_v01/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/public/home/user/anaconda3/envs/qubekit_v01/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/user/anaconda3/envs/qubekit_v01/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/user/anaconda3/envs/qubekit_v01/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/public/home/user/qubekit_doc/qubekit_v01/qubekit/qubekit/cli/run.py", line 128, in run
    workflow = prep_config(
  File "/public/home/user/qubekit_doc/qubekit_v01/qubekit/qubekit/cli/config.py", line 26, in prep_config
    workflow = WorkFlow.parse_file(config_file)
  File "pydantic/main.py", line 569, in pydantic.main.BaseModel.parse_file
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for WorkFlow
torsion_optimisation -> targets -> TorsionProfile_OpenMM -> target_name
  unexpected value; permitted: 'TorsionProfile_SMIRNOFF' (type=value_error.const; given=TorsionProfile_OpenMM; permitted=('TorsionProfile_SMIRNOFF',))

**Comment by jthorton** [comment]
Hi @howlfwq, sorry I forgot to mention that the config file will need to be remade with the new version of QUBEKit as we had to change some things to work with the new fragmentation based workflow.

**Comment by bieniekmateusz** [comment]
Hi @howlfwq , I am pretty sure that both mutex are the  same version, but one is from gcc as in `_openmp_mutex=4.5=1_gcc` and one is from llvm `_openmp_mutex=4.5=1_llvm`. Ie it is more subtle. If the deadlock is the issue, you can use `strace` see it.

**Comment by howlfwq** [comment]
Hi @jthorton, thank you for your quick reply. I have created a new config file. Everything works well except torsion_optimisation. I have attached the qubekit.err file and the optimize.err from torsion_optimisation. The molecule I tried is ethanol.
[optimize_err.txt](https://github.com/qubekit/QUBEKit/files/10266346/optimize_err.txt)
[QUBEKit_err.txt](https://github.com/qubekit/QUBEKit/files/10266347/QUBEKit_err.txt)

**Comment by howlfwq** [comment]
> Hi @howlfwq , I am pretty sure that both mutex are the same version, but one is from gcc as in `_openmp_mutex=4.5=1_gcc` and one is from llvm `_openmp_mutex=4.5=1_llvm`. Ie it is more subtle. If the deadlock is the issue, you can use `strace` see it.

Hi @bieniekmateusz , I checked mine. It is 4.5=1_gnu.
