### ISSUE TITLE
Phosphorous valency 3 works but valency 5 does not work

### ISSUE THREAD

**Issue by anandojha** [qubekit/QUBEKit#360]
Hello, 
I am working on getting the parameters for a ligand in which the phosphorous has a valency of 5, but the sequence of calculation fails with the following error:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aaojha/anaconda3/envs/qubekit/lib/python3.8/site-packages/qubekit/workflow/workflow.py", line 335, in _run_stage
    result_mol = stage.run(
  File "/home/aaojha/anaconda3/envs/qubekit/lib/python3.8/site-packages/qubekit/workflow/helper_stages.py", line 130, in run
    preopt_geometries = self._pre_opt(
  File "/home/aaojha/anaconda3/envs/qubekit/lib/python3.8/site-packages/qubekit/workflow/helper_stages.py", line 250, in _pre_opt
    result_mol, opt_result = result.get()
  File "/home/aaojha/anaconda3/envs/qubekit/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
qcelemental.exceptions.ValidationError: Inconsistent or unspecified chg/mult: sys chg: 0, frag chg: [None], sys mult: 1, frag mult: [None]

However the charge on the system is 0. 

But, if I remove the atoms to make it a valency of 3, the workflow works. 

Please help me in this issue. I am attaching the files:

[files.zip](https://github.com/qubekit/QUBEKit/files/10701454/files.zip)

**Comment by jthorton** [comment]
Hi @anandojha sorry for the delay! This seems to be due to the use of a pdb file as input, we use RDKit to read the file and build the internal models, the issue is that RDKit can not determine bond order from PDBs safely and so assigns each bond an order of 1 which causes issues later in the workflow for you first molecule. I tried saving the molecules as an sdf using pymol and that seems to work fine (see file attached). I would recommend using SDF where possible.

Note that we dont accutally have any parameters for  phosphorous in QUBEKit yet so you will need to provide your own in the config file which are consistent with the rest of the parameters see [here](https://pubs.rsc.org/en/content/articlehtml/2022/cp/d2cp02864f) for more info on how the parameters of the models are fit.
[test.txt](https://github.com/qubekit/QUBEKit/files/10823433/test.txt)
