### ISSUE TITLE
unfixed error in conda repo, fixed in GitHub?

### ISSUE THREAD

**Issue by mkrompiec** [qubekit/QUBEKit#386]
qubekit run -sm CC -n ethane -p 5e
Parametrising molecule with openff_unconstrained-1.3.0.offxml.
/usr/local/lib/python3.10/site-packages/openff/interchange/smirnoff/_create.py:145: UserWarning: Automatically up-converting BondHandler from version 0.3 to 0.4. Consider manually upgrading this BondHandler (or <Bonds> section in an OFFXML file) to 0.4 or newer. For more details, see https://openforcefield.github.io/standards/standards/smirnoff/#bonds.
  _upconvert_bondhandler(force_field["Bonds"])
Molecule parameterised and values stored.
Optimising the molecule using pre_optimisation method gfn2xtb.
Optimising conformers with gfn2xtb:   0%|                 | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/qubekit/engines/geometry_optimiser.py", line 139, in optimise
    initial_mol = molecule.to_qcschema()
  File "/usr/local/lib/python3.10/site-packages/qubekit/molecules/ligand.py", line 1295, in to_qcschema
    if self.coordinates == [] or self.coordinates is None:
ValueError: operands could not be broadcast together with shapes (8,3) (0,)

**Comment by dangelescu** [comment]
I ended up with the same error message during the optimization step no matter the config file options utilized.  Just to mention that i) the Gaussian was not available on the local machine (Ubuntu 22.04 running under Win10) so that all tests relied on psi4 and torchani and ii) packages were installed using mamba.

**Comment by mmagithub** [comment]
got the same, any quick fix ?
