### ISSUE TITLE
Matplotib Version > 3.7.3 Gives a ValueError when using VirtualSites().run()

### ISSUE THREAD

**Issue by bismuthadams1** [qubekit/QUBEKit#391]
Error output 
`Traceback (most recent call last):
  File "/Users/localadmin/Documents/projects/QM_ESP_Psi4/example_scripts/qubekit_charges.py", line 43, in <module>
    qubekit_ligand = vs.run(qubekit_ligand)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/localadmin/mambaforge/envs/openff/lib/python3.11/site-packages/qubekit/nonbonded/virtual_sites.py", line 141, in run
    self._fit(atom_index)
  File "/Users/localadmin/mambaforge/envs/openff/lib/python3.11/site-packages/qubekit/nonbonded/virtual_sites.py", line 910, in _fit
    self._plot(atom_index, site_errors, one_site_coords, two_site_coords)
  File "/Users/localadmin/mambaforge/envs/openff/lib/python3.11/site-packages/qubekit/nonbonded/virtual_sites.py", line 1019, in _plot
    cbar = fig.colorbar(sm)
           ^^^^^^^^^^^^^^^^
  File "/Users/localadmin/mambaforge/envs/openff/lib/python3.11/site-packages/matplotlib/figure.py", line 1285, in colorbar
    raise ValueError(
ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.`

**Comment by bismuthadams1** [comment]
Downgrading from 3.8.0 to 3.7.3 fixed the issue.

**Comment by bismuthadams1** [comment]
Downgrading from 3.8.0 to 3.7.3 fixed the issue.
